packageExtensions:
  eslint-plugin-sort-keys-fix@1.1.1:
    dependencies:
      espree: ^6.1.2
      esutils: ^2.0.2
      natural-compare: ^1.4.0
  eslint-plugin-typescript-sort-keys@1.3.0:
    dependencies:
      globals: ^13.2.0
      json-schema: ^0.2.5
    peerDependencies:
      '@typescript-eslint/parser': ^4.0.1
      typescript: ^4.0.1
  '@typescript-eslint/experimental-utils@2.32.0':
    dependencies:
      json-schema: ^0.2.5

yarnPath: .yarn/releases/yarn-2.2.2.cjs
