[build]
  publish = "public"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "12"
  YARN_FLAGS = "--prefer-offline --frozen-lockfile --no-ignore-optional"
  YARN_VERSION = "1.22.5"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
