[build]
  publish = "public"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "12"
  YARN_FLAGS = "--ignore-optional --frozen-lockfile"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "http://www.keegan.gives/*"
  to = "https://www.keegan.digital/giving-back/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.keegan.gives/*"
  to = "https://www.keegan.digital/giving-back/"
  status = 301
  force = true

[[redirects]]
  from = "http://keegan.gives/*"
  to = "https://www.keegan.digital/giving-back/"
  status = 301
  force = true

[[redirects]]
  from = "https://keegan.gives/*"
  to = "https://www.keegan.digital/giving-back/"
  status = 301
  force = true
