[build]
  publish = "public"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "12"
  YARN_FLAGS = "--no-ignore-optional"
  YARN_VERSION = "1.22.4"

#[[plugins]]
#  package = "netlify-plugin-gatsby-cache"
